import withNuxt from './.nuxt/eslint.config.mjs';
import { baseEslintConfig } from '@fastcat/eslint-config';

export default withNuxt(...baseEslintConfig)
  .append({
    ignores: [
      '.output/**',
      '.nuxt/**',
      'dist/**',
      'coverage/**',
      'node_modules/**',
      '**/*.d.ts',
      // ts-rs generated bindings (Rust is the source of truth; do not lint/format).
      'src/types/generated/**',
      // Vendored font manifest (generated by scripts/vendor-fonts.mjs on postinstall).
      'src/utils/video-editor/font-manifest.ts',
    ],
  })
  .append({
    rules: {
      'vue/multi-word-component-names': 'error',
      'vue/require-default-prop': 'error',
      // Diagnostic logging must go through ~/utils/dev-logger (gated by env and
      // mockable in tests).
      'no-console': 'error',
    },
  })
  .append({
    files: ['test/**/*.ts', 'test/**/*.vue'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-extraneous-class': 'off',
      '@typescript-eslint/no-dynamic-delete': 'off',
      '@typescript-eslint/no-useless-constructor': 'off',
      '@typescript-eslint/unified-signatures': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      'no-useless-escape': 'off',
      'vue/multi-word-component-names': 'off',
      'vue/require-default-prop': 'off',
      'no-empty': 'off',
      'no-unsafe-finally': 'off',
      'no-console': 'off',
    },
  })
  .append({
    files: ['src/**/*.vue'],
    rules: {
      '@typescript-eslint/unified-signatures': 'off',
    },
  })
  .append({
    files: ['src/pages/**/*.vue', 'src/layouts/**/*.vue'],
    rules: {
      'vue/multi-word-component-names': 'off',
    },
  });
