/**
 * Vendors the editor's text-tool fonts from the `@fontsource/*` npm packages
 * into the static build so they are served SAME-ORIGIN.
 *
 * This is required once the web build ships COOP/COEP
 * (`Cross-Origin-Embedder-Policy: require-corp`): under cross-origin isolation
 * the browser blocks cross-origin subresources that lack CORP, and it lets the
 * video-core / export workers register the faces without a cross-origin
 * `fetch()`. Sourcing from npm (not scraping Google's CSS) means the build
 * needs no network and the fonts are pinned by the lockfile.
 *
 * Copies the selected `.woff2` files into `public/fonts/` and emits a bundled
 * TS manifest (family + weight + unicode-range + same-origin url) consumed by
 * `load-fonts.ts`. Runs on `postinstall`; re-run manually via `pnpm fonts:vendor`.
 */
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FONTSOURCE_DIR = resolve(ROOT, 'node_modules/@fontsource');
const OUT_DIR = resolve(ROOT, 'public/fonts');
const MANIFEST_TS = resolve(ROOT, 'src/utils/video-editor/font-manifest.ts');

// Editor supports en + ru → keep only these subsets to bound the payload.
const SUBSET_ALLOWLIST = ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'];

// pkg = @fontsource package name, family = CSS font-family, weights = static
// instances the text tool exposes. Subsets absent from a package are skipped.
const FONTS = [
  { pkg: 'inter', family: 'Inter', weights: ['400', '700'] },
  { pkg: 'roboto', family: 'Roboto', weights: ['400', '700'] },
  { pkg: 'montserrat', family: 'Montserrat', weights: ['400', '700'] },
  { pkg: 'oswald', family: 'Oswald', weights: ['400', '700'] },
  { pkg: 'noto-sans', family: 'Noto Sans', weights: ['400', '700'] },
  { pkg: 'playfair-display', family: 'Playfair Display', weights: ['400', '700'] },
  { pkg: 'bebas-neue', family: 'Bebas Neue', weights: ['400'] },
  { pkg: 'rubik', family: 'Rubik', weights: ['400', '700'] },
  { pkg: 'fredoka', family: 'Fredoka', weights: ['400', '700'] },
  { pkg: 'jetbrains-mono', family: 'JetBrains Mono', weights: ['400', '700'] },
  { pkg: 'caveat', family: 'Caveat', weights: ['400', '700'] },
];

/**
 * Parse `<pkg>/<weight>.css` into `{ [subset]: unicodeRange }` by pairing each
 * `/* <pkg>-<subset>-<weight>-normal *␦/` marker with its `unicode-range:` line.
 */
async function readUnicodeRanges(pkg, weight) {
  const cssPath = resolve(FONTSOURCE_DIR, pkg, `${weight}.css`);
  const css = await readFile(cssPath, 'utf8');
  const ranges = {};
  const re = new RegExp(
    `/\\*\\s*${pkg}-([a-z-]+)-${weight}-normal\\s*\\*/[\\s\\S]*?unicode-range:\\s*([^;]+);`,
    'g',
  );
  for (const m of css.matchAll(re)) ranges[m[1]] = m[2].trim();
  return ranges;
}

async function fileExists(path) {
  try {
    await readFile(path);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const entries = [];
  let copied = 0;

  for (const { pkg, family, weights } of FONTS) {
    for (const weight of weights) {
      const ranges = await readUnicodeRanges(pkg, weight);
      for (const subset of SUBSET_ALLOWLIST) {
        const fileName = `${pkg}-${subset}-${weight}-normal.woff2`;
        const srcPath = resolve(FONTSOURCE_DIR, pkg, 'files', fileName);
        if (!(await fileExists(srcPath))) continue; // subset not shipped for this family
        await copyFile(srcPath, resolve(OUT_DIR, fileName));
        copied += 1;
        entries.push({
          family,
          weight,
          style: 'normal',
          unicodeRange: ranges[subset] ?? '',
          url: `/fonts/${fileName}`,
        });
      }
    }
  }

  if (entries.length === 0) {
    throw new Error('No fonts vendored — is @fontsource installed? Run pnpm install first.');
  }

  const ts = `// AUTO-GENERATED by scripts/vendor-fonts.mjs — do not edit by hand.
// Sourced from the pinned @fontsource/* packages; run \`pnpm fonts:vendor\` to
// regenerate after changing the FONTS list in that script.
export interface VendoredFontFace {
  family: string;
  weight: string;
  style: string;
  /** CSS unicode-range for the subset ('' means no restriction). */
  unicodeRange: string;
  /** Same-origin URL under the static /fonts/ dir. */
  url: string;
}

export const VENDORED_FONTS: readonly VendoredFontFace[] = ${JSON.stringify(entries, null, 2)};
`;
  await mkdir(dirname(MANIFEST_TS), { recursive: true });
  await writeFile(MANIFEST_TS, ts);

  const families = new Set(entries.map((e) => e.family));
  console.log(`Vendored ${copied} woff2 files across ${families.size} families into public/fonts/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
