// AUTO-GENERATED by scripts/vendor-fonts.mjs — do not edit by hand.
// Sourced from the pinned @fontsource/* packages; run `pnpm fonts:vendor` to
// regenerate after changing the FONTS list in that script.
export interface VendoredFontFace {
  family: string;
  weight: string;
  style: string;
  /** CSS unicode-range for the subset ('' means no restriction). */
  unicodeRange: string;
  /** Same-origin URL under the static /fonts/ dir. */
  url: string;
}

export const VENDORED_FONTS: readonly VendoredFontFace[] = [
  {
    "family": "Inter",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/inter-latin-400-normal.woff2"
  },
  {
    "family": "Inter",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/inter-latin-ext-400-normal.woff2"
  },
  {
    "family": "Inter",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/inter-cyrillic-400-normal.woff2"
  },
  {
    "family": "Inter",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/inter-cyrillic-ext-400-normal.woff2"
  },
  {
    "family": "Inter",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/inter-latin-700-normal.woff2"
  },
  {
    "family": "Inter",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/inter-latin-ext-700-normal.woff2"
  },
  {
    "family": "Inter",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/inter-cyrillic-700-normal.woff2"
  },
  {
    "family": "Inter",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/inter-cyrillic-ext-700-normal.woff2"
  },
  {
    "family": "Roboto",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/roboto-latin-400-normal.woff2"
  },
  {
    "family": "Roboto",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/roboto-latin-ext-400-normal.woff2"
  },
  {
    "family": "Roboto",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/roboto-cyrillic-400-normal.woff2"
  },
  {
    "family": "Roboto",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/roboto-cyrillic-ext-400-normal.woff2"
  },
  {
    "family": "Roboto",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/roboto-latin-700-normal.woff2"
  },
  {
    "family": "Roboto",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/roboto-latin-ext-700-normal.woff2"
  },
  {
    "family": "Roboto",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/roboto-cyrillic-700-normal.woff2"
  },
  {
    "family": "Roboto",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/roboto-cyrillic-ext-700-normal.woff2"
  },
  {
    "family": "Montserrat",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/montserrat-latin-400-normal.woff2"
  },
  {
    "family": "Montserrat",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/montserrat-latin-ext-400-normal.woff2"
  },
  {
    "family": "Montserrat",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/montserrat-cyrillic-400-normal.woff2"
  },
  {
    "family": "Montserrat",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/montserrat-cyrillic-ext-400-normal.woff2"
  },
  {
    "family": "Montserrat",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/montserrat-latin-700-normal.woff2"
  },
  {
    "family": "Montserrat",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/montserrat-latin-ext-700-normal.woff2"
  },
  {
    "family": "Montserrat",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/montserrat-cyrillic-700-normal.woff2"
  },
  {
    "family": "Montserrat",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/montserrat-cyrillic-ext-700-normal.woff2"
  },
  {
    "family": "Oswald",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/oswald-latin-400-normal.woff2"
  },
  {
    "family": "Oswald",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/oswald-latin-ext-400-normal.woff2"
  },
  {
    "family": "Oswald",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/oswald-cyrillic-400-normal.woff2"
  },
  {
    "family": "Oswald",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/oswald-cyrillic-ext-400-normal.woff2"
  },
  {
    "family": "Oswald",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/oswald-latin-700-normal.woff2"
  },
  {
    "family": "Oswald",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/oswald-latin-ext-700-normal.woff2"
  },
  {
    "family": "Oswald",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/oswald-cyrillic-700-normal.woff2"
  },
  {
    "family": "Oswald",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/oswald-cyrillic-ext-700-normal.woff2"
  },
  {
    "family": "Noto Sans",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/noto-sans-latin-400-normal.woff2"
  },
  {
    "family": "Noto Sans",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/noto-sans-latin-ext-400-normal.woff2"
  },
  {
    "family": "Noto Sans",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/noto-sans-cyrillic-400-normal.woff2"
  },
  {
    "family": "Noto Sans",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/noto-sans-cyrillic-ext-400-normal.woff2"
  },
  {
    "family": "Noto Sans",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/noto-sans-latin-700-normal.woff2"
  },
  {
    "family": "Noto Sans",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/noto-sans-latin-ext-700-normal.woff2"
  },
  {
    "family": "Noto Sans",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/noto-sans-cyrillic-700-normal.woff2"
  },
  {
    "family": "Noto Sans",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/noto-sans-cyrillic-ext-700-normal.woff2"
  },
  {
    "family": "Playfair Display",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/playfair-display-latin-400-normal.woff2"
  },
  {
    "family": "Playfair Display",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/playfair-display-latin-ext-400-normal.woff2"
  },
  {
    "family": "Playfair Display",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/playfair-display-cyrillic-400-normal.woff2"
  },
  {
    "family": "Playfair Display",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/playfair-display-latin-700-normal.woff2"
  },
  {
    "family": "Playfair Display",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/playfair-display-latin-ext-700-normal.woff2"
  },
  {
    "family": "Playfair Display",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/playfair-display-cyrillic-700-normal.woff2"
  },
  {
    "family": "Bebas Neue",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/bebas-neue-latin-400-normal.woff2"
  },
  {
    "family": "Bebas Neue",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/bebas-neue-latin-ext-400-normal.woff2"
  },
  {
    "family": "Rubik",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/rubik-latin-400-normal.woff2"
  },
  {
    "family": "Rubik",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/rubik-latin-ext-400-normal.woff2"
  },
  {
    "family": "Rubik",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/rubik-cyrillic-400-normal.woff2"
  },
  {
    "family": "Rubik",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/rubik-cyrillic-ext-400-normal.woff2"
  },
  {
    "family": "Rubik",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/rubik-latin-700-normal.woff2"
  },
  {
    "family": "Rubik",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/rubik-latin-ext-700-normal.woff2"
  },
  {
    "family": "Rubik",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/rubik-cyrillic-700-normal.woff2"
  },
  {
    "family": "Rubik",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/rubik-cyrillic-ext-700-normal.woff2"
  },
  {
    "family": "Fredoka",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/fredoka-latin-400-normal.woff2"
  },
  {
    "family": "Fredoka",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/fredoka-latin-ext-400-normal.woff2"
  },
  {
    "family": "Fredoka",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/fredoka-latin-700-normal.woff2"
  },
  {
    "family": "Fredoka",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/fredoka-latin-ext-700-normal.woff2"
  },
  {
    "family": "JetBrains Mono",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/jetbrains-mono-latin-400-normal.woff2"
  },
  {
    "family": "JetBrains Mono",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/jetbrains-mono-latin-ext-400-normal.woff2"
  },
  {
    "family": "JetBrains Mono",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/jetbrains-mono-cyrillic-400-normal.woff2"
  },
  {
    "family": "JetBrains Mono",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/jetbrains-mono-cyrillic-ext-400-normal.woff2"
  },
  {
    "family": "JetBrains Mono",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/jetbrains-mono-latin-700-normal.woff2"
  },
  {
    "family": "JetBrains Mono",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/jetbrains-mono-latin-ext-700-normal.woff2"
  },
  {
    "family": "JetBrains Mono",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/jetbrains-mono-cyrillic-700-normal.woff2"
  },
  {
    "family": "JetBrains Mono",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/jetbrains-mono-cyrillic-ext-700-normal.woff2"
  },
  {
    "family": "Caveat",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/caveat-latin-400-normal.woff2"
  },
  {
    "family": "Caveat",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/caveat-latin-ext-400-normal.woff2"
  },
  {
    "family": "Caveat",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/caveat-cyrillic-400-normal.woff2"
  },
  {
    "family": "Caveat",
    "weight": "400",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/caveat-cyrillic-ext-400-normal.woff2"
  },
  {
    "family": "Caveat",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
    "url": "/fonts/caveat-latin-700-normal.woff2"
  },
  {
    "family": "Caveat",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF",
    "url": "/fonts/caveat-latin-ext-700-normal.woff2"
  },
  {
    "family": "Caveat",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
    "url": "/fonts/caveat-cyrillic-700-normal.woff2"
  },
  {
    "family": "Caveat",
    "weight": "700",
    "style": "normal",
    "unicodeRange": "U+0460-052F,U+1C80-1C8A,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F",
    "url": "/fonts/caveat-cyrillic-ext-700-normal.woff2"
  }
];
